


#define	WOLFSSL_SMALL_STACK
#define	OPENSSL_EXTRA
#define	HAVE_ECC
#define	HAVE_ECC_DHE
#define	HAVE_ALL_CURVES
#define	WOLFSSL_CUSTOM_CURVES
#define	HAVE_ECC_SECPR2
#define	HAVE_ECC_SECPR3
#define	HAVE_ECC_KOBLITZ
#define	HAVE_ECC_BRAINPOOL
#define	HAVE_COMP_KEY
#define	WC_NO_HARDEN
#define	WOLFSSL_MIN_ECC_BITS	32
#define	WOLFSSL_CERT_EXT
